---
title: "About"
---

This website is dedicated to the MetaPaleo research project. MetaPaleo is a series of interactive, collaborative and openly participatory sub-projects investigating large-scale aspects of Palaeontology research. Current projects include:

 1. [OpenPaleo](https://github.com/Meta-Paleo/OpenPaleo)
 1. [TimeSeries](https://github.com/Meta-Paleo/TimeSeries)
 1. [Peer Review Transparency](https://github.com/Meta-Paleo/Peer-Review-Transparency)
 1. [TetraTime](https://github.com/Meta-Paleo/TetraTime)
 
# An Open project

Want to propose something else? All data, code, methods, and live results are available on the [GitHub](https://github.com/Meta-Paleo/) project page. 

Anyone can contribute anything they want to this, irrespective of past experience.

# About me

I am an independent/rogue researcher, working on both Palaeontology and aspects of scholarly communication and open science. I received my PhD from Imperial College in 2017, where I was awarded the Janet Watson prize for research excellence. 

Details of my research are all available on my [personal website](http://fossilsandshit.com/research/).

Contact: [email](mailto:jon.tennant.2@gmail.com) or [Twitter](https://twitter.com/protohedgehog)